### ISSUE TITLE
Looking to contribute to development

### ISSUE THREAD

**Issue by dkozickis** [SagemCassiopee/php-taf-decoder#1]
Hi guys,

Looking to contribute to the development of this decoder. 
Have personal interest in it for one of my projects.

If you could please commit initial draft and whip up some code structure guidelines, I might be able to contribute and speed up the process? Imagine you're looking at structure similar to metar-decoder, with and added layer of class for TAF periods?

**Comment by laurentkoka** [comment]
Hi, 

Thanks for your interest in our project. We will commit the initial version of the code in the next few weeks. Yes, the structure should be similar to the METAR decoder Your potential contribution is appreciated !

**Comment by jpjoux** [comment]
@JohnieWalker Hi Johnie, we have started the development and made the first structure og the php_taf_decoder.  We can find an agreement, in order you help us on the developments and define on which chunk you can work on.
How can we proceed , on which chunk decoder you want to work on ?

**Comment by dkozickis** [comment]
Whichever chunk you feel safe giving away to someone outside company. At
this point I don't quite understand how you decided to iterate over
different forecast probabilities/periods (FM/PROB/TEMPO) in one TAF.
Reading source from mobile, so maybe I'm missing something :)

**Comment by jpjoux** [comment]
Hi @JohnieWalker 
We have finished a first version of the php_taf_decoder. You can launch a first test session in order to improve the decoder. Do not hesitate to come back to us and propose ideas / updates

I will close this topics
