### ISSUE TITLE
ForecastPeriod - toHour should include 24 as valid

### ISSUE THREAD

**Issue by hartungt** [SagemCassiopee/php-taf-decoder#19]
Hi there,

the ForecastPeriod::isValid tests on "> 23". This should be "> 24" for the toHour field.

Example:
`TAF FAOR 061600Z 0618/0724 28010KT CAVOK 
BECMG 0622/0624 22007KT 
FM070400 02007KT CAVOK`

See here: https://www.aviationweather.gov/static/help/taf-decode.php#Valid
The valid period ending isn't 0700 but 0624.

**Comment by jpjoux** [comment]
Thnaks for your feedback, an old PR was provided by @icaroce .
It has been integrated. 
I propose you to write a missing test in order to validate the integrated modification

**Comment by hartungt** [comment]
Thanks. Works fine now.
