### ISSUE TITLE
valid TAF reaching into following month

### ISSUE THREAD

**Issue by hartungt** [SagemCassiopee/php-taf-decoder#20]
Today all TAF's are marked invalid. Example:

`TAF EDDF 311100Z 3112/0118 08005KT 9999 FEW025 BECMG 3117/3119 VRB02KT PROB40 TEMPO 0102/0110 4000 MIFG PROB30 TEMPO 0103/0110 1200 BCFG BKN002 BECMG 0112/0114 21005KT`

A quick look into the code. I would say it is ForecastPeriod.php -> isValid(). 

```
// check that start is before end
if ($this->getFromDay() > $this->getToDay()) {
    return false;
}
```

Obviously 31 (Oktober) is greater than 01 (November)

**Comment by jpjoux** [comment]
@hartungt 
The proposed code in the PR #21  have been accepted. I close the issue.
Thanks for your contribution.
